### ISSUE TITLE
小程序登录流程(记住密码)

### ISSUE THREAD

**Issue by xbinator** [Abouerp/applet-library#1]
1. 小程序 第一次 进入, wx.login() 获取 code
2. 小程序发送 wx.request() code, 开发者服务器
3. 开发者服务器 将 根据 登录凭证接口 发送数据, 获取 ession_key  + openId
4. 匹配 开发者服务器的数据库, 如果匹配到数据, 返回用户信息, 如果未匹配到, 返回为空, 
5. 小程序 根据返回的数据 展示 . 用户未登录, 将显示登录 按钮, 小程序提供微信一键登录 获取微信电话, 将不需要密码和用户自己输入密码与电话, 实现登录.

**Comment by Abouerp** [comment]
相同的登陆接口，如果是手机+密码登陆，发mobile和password，如果是小程序授权，则只发一个参数jsCode，后台判断哪种模式，如果登陆成功返回token，登陆失败401

**Comment by xbinator** [comment]
还要给我一个接口, 类似 get /user/me

**Comment by Abouerp** [comment]
第4点的匹配信息拿什么匹配，没授权拿到的只有nickName那些基础信息而已

**Comment by xbinator** [comment]
openId

**Comment by xbinator** [comment]
这种接口 就类似 get /user/me  我需要知道用户是否登录过,

**Comment by Abouerp** [comment]
那么这样微信新用户没注册之前都是没法登陆的

**Comment by xbinator** [comment]
那就每次登录吧

**Comment by Abouerp** [comment]
/api/user/me get请求   可以拿到个人信息，但是header需要携带token

**Comment by xbinator** [comment]
登录后才能获取的  token ?

**Comment by Abouerp** [comment]
是的，一个token对应一个登陆用户

**Comment by xbinator** [comment]
那行, 那就是用户每次进入小程序 必须都要登录,

**Comment by Abouerp** [comment]
也可以用微信直接登陆，发送jsCode，我后台请求数据到注册系统注册这个用户，然后注册完成返回token给前台，但是这需要设置默认密码，这不安全，所以不建议这么操作

**Comment by xbinator** [comment]
嗯, 简单来吧

**Comment by xbinator** [comment]
安全 就看我们设计了

**Comment by Abouerp** [comment]
先就登陆吧，把主体的功能先实现

**Comment by xbinator** [comment]
嗯, 以后再有时间完善吧
